# Generated by Django 6.0.1 on 2026-01-08 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="commentary",
            old_name="user",
            new_name="author",
        ),
        migrations.RenameField(
            model_name="commentary",
            old_name="content",
            new_name="text",
        ),
        migrations.RenameField(
            model_name="post",
            old_name="owner",
            new_name="author",
        ),
    ]
